services:
  postgres:
    image: postgres
    restart: always
    env_file:
      - ./.env.development
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '${POSTGRES_PORT:-5432}:5432'
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis
    restart: always
    env_file:
      - ./.env.development
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    ports:
      - '${REDIS_PORT:-6379}:6379'
    volumes:
      - redis:/data

volumes:
  postgres:
  redis:
